### ISSUE TITLE
Write Place JSON to disk using IObjectModifiedEvent handler

### ISSUE THREAD

**Issue by sgillies** [isawnyu/PleiadesEntity#3]
@paregorios Check out https://github.com/isawnyu/PleiadesEntity/blob/master/event.py#L27. Just above this line would be where to add code that writes JSON to disk and that would make sure that you got JSON written whenever someone edited one of its names or locations. Important to make sure than JSON writing tracks the writes to the catalog.

You'll need to add another handler for IObjectModifiedEvents involving Places. Something like:

```
@adapter(IPlace, IObjectModifiedEvent)
def placeJSONSubscriber(obj, event):
    # write JSON to disk
```

and then register it in configure.zcml.

Lemme know how it goes. I'm glad to see this work happening!

**Comment by paregorios** [comment]
won't fix. Obviated by Pleiades 3 upgrades.
